default_options: &default_options
  store_options:
    max_age: <%= 60.days.to_i %>
    namespace: <%= Rails.env %>

default_connection: &default_connection
  database: cache

default: &default
  <<: *default_connection
  <<: *default_options

development: *default
test: *default_options
beta: *default
staging: *default
# Only configure Solid Cache database connection if using solid_cache_store
production:
  <<: *default_options
<% if ENV.fetch("CACHE_STORE", "solid_cache_store") == "solid_cache_store" %>
  database: cache
<% end %>
